### ISSUE TITLE
Error when generation iOS splash screen

### ISSUE THREAD

**Issue by jesusrp98** [henriquearthur/flutter_native_splash#1]
First, I want to say this package is great. Super useful and I love it!

About the error, it seems that my project doesn't have the `AppDelegate.m` file, instead I have `AppDelegate.swift`, since I'm using Swift instead of Objective-C.

Here is the output:
```
> flutter pub pub run flutter_native_splash:create
[Android] Creating splash images
[Android] Updating launch_background.xml with splash image path
[iOS] Creating splash images
[iOS] Updating LaunchScreen.storyboard with width, height and color
[Android] No colors.xml file found in your Android project
[Android] Creating colors.xml file and adding it to your Android project
[Android] Updating styles.xml with full screen mode setting
[iOS] Updating Info.plist and AppDelegate.m for status bar hidden/visible
Unhandled exception:
FileSystemException: Cannot open file, path = 'ios/Runner/AppDelegate.m' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:9)
#1      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#6      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
pub finished with exit code 255
```

**Comment by henriquearthur** [comment]
Thank you for reporting this.

I have not considered projects using Swift instead of Objective-C. I will fix this later today by adding support to AppDelegate.swift.

The splash screen was generated in your project, but the status bar will remain hidden after app loaded because the code to show the status bar is in AppDelegate.

**Comment by jesusrp98** [comment]
OK, thank you very much!

Looking forward to the fix! :)

**Comment by jesusrp98** [comment]
Thank you very much, going to test this out in a couple hours.
I could test that on iOS in real hardware for you no problem!
