### ISSUE TITLE
CantFindMainActivityPath Error on run create 

### ISSUE THREAD

**Issue by Abaddon-88** [henriquearthur/flutter_native_splash#44]
I use flutter 1.9.1 added the package to pubspec dependencies (flutter_native_splash 0.1.9) and create the entry 

flutter_native_splash:
  image: assets/images/launcher_icon.jpg
  color: "42a5f5"
  fill: true 

If i run the the statement the error appear. If I try a new projekt it work, but if i try my old projekt the error appear. I only added some permissions to the androidManifest file. Can you please give me more infos what the exact problem is with this error?

```
Unhandled exception:
*** ERROR [flutter_native_splash] ***
CantFindMainActivityPath
Not able to determinate MainActivity path. Maybe the problem is your package path OR your AndroidManifest.xml 'package' attribute on manifest.
#0      _javaOrKotlin (package:flutter_native_splash/android.dart:335:5)
<asynchronous suspension>
#1      _applyMainActivityUpdate (package:flutter_native_splash/android.dart:308:33)
<asynchronous suspension>
#2      createSplash (package:flutter_native_splash/android.dart:42:9)
<asynchronous suspension>
#3      createSplash (package:flutter_native_splash/flutter_native_splash.dart:20:11)
<asynchronous suspension>
#4      main (file:///Users/bastiangobet/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-0.1.9/bin/create.dart:5:3)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
pub finished with exit code 255
```

**Comment by henriquearthur** [comment]
Can you share your `AndroidManifest.xml`?

**Comment by Abaddon-88** [comment]
i have delete the android part of the app and rebuild it. Then the plugin work fine. Thanks
