### ISSUE TITLE
error 255 when 'black' #000000 background tried. all other colours including white #ffffff fine.

### ISSUE THREAD

**Issue by lubi888** [henriquearthur/flutter_native_splash#6]
Hi again, @henriquearthur ,

I tried a black background and got this error. 

```
flutter pub pub run flutter_native_splash:create
Unhandled exception:
type 'int' is not a subtype of type 'String'
#0      createSplash (package:flutter_native_splash/flutter_native_splash.dart:15:10)
<asynchronous suspension>
#1      main (file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-0.1.6/bin/create.dart:5:3)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
pub finished with exit code 255
```

Every other colour, including 'white' #ffffff works fine for me. 

Is black a colour or an absence of colour and light?! That's possibly a [physics question](https://physics.stackexchange.com/questions/92535/is-black-a-color-or-absence-of-color).

**Comment by lubi888** [comment]
Hi Herique,

Yeah, take your time. There's no rush.

In the meantime I just put in a 95% black from [w3 schools](https://www.w3schools.com/colors/colors_picker.asp) color picker and it works fine.

  `color: 0d0d0d`   gives me as near to black '000000' as possible

Does the code think '000000' is 0 the int and not '000000' the string? I'll let you handle that.

Thanks, H.

**Comment by bishosamer** [comment]
im getting the same issue it seems that it doesnt like 0's, i tried 008e93 and it gives the same error

**Comment by lubi888** [comment]
Hi again @henriquearthur 

Looking forward to giving this a try today. So this was a yaml issue and not a prob for dart? Sounds about right.

I'll give it a go a bit later because right now 'pub.dev' website is down and 'flutter pub get' is not working. A bit embarrassing for Google. Must be hard for the developers like you right now. 

Anyway, thanks again for all your work and contributions to the flutter community. Ciao
