### ISSUE TITLE
bool is not a subtype of type 'String'

### ISSUE THREAD

**Issue by alvinvin00** [henriquearthur/flutter_native_splash#80]
My project are using Kotlin and Android Embedding v2 enabled.

I'm confused because when i'm diving to source code, there's nothing that indicates a function retrieved wrong return type.

Stack Trace :

```
D:\Eliteguard\sg_absence>flutter pub run flutter_native_splash:create
[Android] Creating splash images
[Android] Updating launch_background.xml with splash image path
[Android] Updating colors.xml with color for splash screen background
[Android] Updating styles.xml with full screen mode setting
Unhandled exception:
type 'bool' is not a subtype of type 'String'
#0      _javaOrKotlin (package:flutter_native_splash/android.dart:330:12)
<asynchronous suspension>
#1      _applyMainActivityUpdate (package:flutter_native_splash/android.dart:308:33)
#2      createSplash (package:flutter_native_splash/android.dart:42:9)
<asynchronous suspension>
#3      createSplash (package:flutter_native_splash/flutter_native_splash.dart:20:11)
<asynchronous suspension>
#4      main (file:///C:/Users/Alvin/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_native_splash-0.1.9/bin/create.dart:5:3)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```

**Comment by jonbhanson** [comment]
Can you share your flutter_native_splash settings from your pubspec.yaml or flutter_native_splash.yaml? That would help in diagnosis.

**Comment by alvinvin00** [comment]
hello there, it's been a long time since i created this issue so maybe a lot has changed since then. I'll try to refire the command, see if it still persists

**Comment by jonbhanson** [comment]
Glad to hear it's working ok.  👍🏻
